version: 2
jobs:
  build:
    working_directory: ~/sentry
    docker:
      - image: circleci/python:3.6.3
        environment:
         AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
         AWS_REGION: $AWS_REGION
         AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

    steps:
      - checkout

      - restore_cache:
         key: sentry-{{ .Branch }}-{{ checksum "build-requirements.txt" }}

      - run:
         command: |
           sudo pip install -r build-requirements.txt

      - save_cache:
         key: sentry-{{ .Branch }}-{{ checksum "build-requirements.txt" }}
         paths:
          - "sentry"

      - run:
          name: Setup AWS credentials
          command: |
            mkdir ~/.aws
            printf "[profile eb-cli]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/config
      
      - run:
          command: ./bin/deploy
